add spelling checker
koordinator-sh/website pull request #30
Opened 2022-04-08 12:17 UTC by hormes

Signed-off-by: Fansong Zeng <fanster.z@gmail.com>

2022-04-08 12:21 UTC, hormes commented
/assign jasonliu747

2022-04-08 15:09 UTC, jasonliu747 commented
fix #29

2022-04-08 15:10 UTC, jasonliu747 commented
Fix #29

2022-04-11 02:52 UTC, FillZpp commented on .github/workflows/spelling_action.yml
> +on: push
```yaml
on:
  push: {}
  pull_request: {}
```

2022-04-11 08:45 UTC, hormes commented on .github/workflows/spelling_action.yml
> +on: push
done

2022-04-11 08:48 UTC, FillZpp commented on .github/workflows/spelling_action.yml
> +on: push
now you can see the failed check...

2022-04-11 08:54 UTC, jasonliu747 requested changes
Need a rich word list.

2022-04-11 11:44 UTC, jasonliu747 approved these changes
/lgtm

2022-04-11 13:08 UTC, hormes commented
/hold

2022-04-11 13:10 UTC, hormes commented
word list will be too long to maintain

2022-04-13 06:40 UTC, jasonliu747 commented
there are severals actions provided by reviewdog, we can use them to do spell check.
https://github.com/reviewdog/reviewdog

2022-10-10 06:28 UTC, hormes commented
/close

2022-10-10 06:28 UTC, closed without merging