add more installation dependency description
koordinator-sh/website pull request #50
Opened 2022-05-22 10:31 UTC by LambdaHJ

add more document for installation.

2022-05-31 09:06 UTC, hormes commented on docs/installation.md
> +For full features, koordinator requires **linux kernel 4.19** or higher.
koordinator recommands **linux kernel 4.19** or higher.

2022-06-01 06:34 UTC, eahydra requested changes

2022-06-01 06:34 UTC, eahydra commented on docs/installation.md
> +you can get more info form [here](https://kubernetes.io/docs/reference/command-line-tools-reference/kubelet/).
typo: form -> from

2022-08-01 12:02 UTC, eahydra commented
/lgtm
/approve

2022-08-04 06:50 UTC, merged